id: P007095
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD362
  title: ཀྲུང་གོའི་ལོ་རྒྱུས་རིག་གནས་གྲགས་ཅན་གྲོང་ཁྱེར། ལྷ་ས།
  author: ''
  volumes:
    a5d2b5bcefbb49d4898981851ed97839:
      image_group_id: I2PD17753
      title: ''
      volume_number: 1
      total_pages: 562
ebook_metadata:
  title: ཀྲུང་གོའི་ལོ་རྒྱུས་རིག་གནས་གྲགས་ཅན་གྲོང་ཁྱེར། ལྷ་ས།
  author: ''
  sku: P007095
  cover: cover.jpg
  layers:
  - pagination
