id: I866DB64C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T05:44:17+00:00'
last_modified: '2022-06-09T04:49:36.667607+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD362
  title: ཀྲུང་གོའི་ལོ་རྒྱུས་རིག་གནས་གྲགས་ཅན་གྲོང་ཁྱེར། ལྷ་ས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A9AA:
      image_group_id: I2PD17753
      title: Volume 1 of krung go'i lo rgyus rig gnas grags can grong khyer/_lha sa/
      total_pages: 562
      order: 1
      base_file: A9AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
